### ISSUE TITLE
Thanks A Lot !

### ISSUE THREAD

**Issue by guiyang882** [galeone/dynamic-training-bench#4]
Dear Sir,
You open source code help me a lot !

thx !

**Comment by galeone** [comment]
Hi @liuguiyangnwpu ! Thank you for the kind words!

I just made a complete refactoring of dtb (and it's renaming to DyTB instead of DTB): now you can use it as a library in your python application and not only as a CLI tool.

Your previous code will work in the same way, just use the `train.py` and `evaluate.py` script you can find in the `scripts` folder.

Since you used DyTB, do you have any suggestion?

Remember that any contribution is welcome, so if you want to contribute in any way feel free to open isseus and/or send pull requests .

*P.S*: you can install DyTB via pip if you want to use it in a python script, in the usual python way: `pip install dytb`.

**Comment by guiyang882** [comment]
ok !
I am running the SAE model to train my own airplane dataset.

thx !
